// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskAPI.DataAccess;

namespace TaskAPI.DataAccess.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20220131022936_AuthorEntityAndData")]
    partial class AuthorEntityAndData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TaskAPI.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Supun Vindula"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Kushini Kalupahana"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Maneesha Randeniya"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Basuru Wickramarachchi"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            AuthorId = 1,
                            Created = new DateTime(2022, 1, 31, 7, 59, 36, 578, DateTimeKind.Local).AddTicks(371),
                            Description = "Get some text books for school",
                            Due = new DateTime(2022, 2, 5, 7, 59, 36, 581, DateTimeKind.Local).AddTicks(7799),
                            Status = 0,
                            Title = "Get books for school - DB"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 2,
                            Created = new DateTime(2022, 1, 31, 7, 59, 36, 581, DateTimeKind.Local).AddTicks(8740),
                            Description = "Buy from Daraz",
                            Due = new DateTime(2022, 2, 3, 7, 59, 36, 581, DateTimeKind.Local).AddTicks(8743),
                            Status = 2,
                            Title = "Get a headphone - DB"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 1,
                            Created = new DateTime(2022, 1, 31, 7, 59, 36, 581, DateTimeKind.Local).AddTicks(8760),
                            Description = "To protect from mosquitos",
                            Due = new DateTime(2022, 2, 4, 7, 59, 36, 581, DateTimeKind.Local).AddTicks(8761),
                            Status = 0,
                            Title = "Put a cover to the window - DB"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Todo", b =>
                {
                    b.HasOne("TaskAPI.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
